### ISSUE TITLE
gradle task run is failed

### ISSUE THREAD

**Issue by ltorok** [HanSolo/TouchSlider#1]
After enter this command 
**gradlew.bat run -Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot"**
in Windows CMD console I get this:
![image](https://user-images.githubusercontent.com/7220540/85547351-1b35b480-b61e-11ea-820f-2250b7611fef.png)

**Comment by HanSolo** [comment]
switched back to gradle 6.3, could you try to run gradlew clean build again

**Comment by HanSolo** [comment]
Oh...now I see, that is because I had the application plugin in the build.gradle file. I removed that because you need to run gradlew Demo :)

**Comment by ltorok** [comment]
Thanks. It is ok now.
